### ISSUE TITLE
Time to split Extensions in 2 categories?

### ISSUE THREAD

**Issue by giuseppemorelli** [aleron75/mageres#36]
Hi @aleron75 ,
I'd like to suggest you that it's time to split Extensions in 2 categories or create a subcategory for Extensions

## Estensions M1
...
## Estensions M2
...

------------------------

### M1
...
### M2
...

I don't know which is better.
What do you think?

**Comment by aleron75** [comment]
Hi @giuseppemorelli, I would prefer the second option.

Feel free to submit your proposed changes, remember that changes should be applied to the `resources.csv` file and that the `README.md` should be generated through:

`php csv2md.php resources.csv README.md`

Thank you!

**Comment by giuseppemorelli** [comment]
Hi @aleron75 ,
pull request sent related with this issue.
Thank you!
