### ISSUE TITLE
Magento 1 Certification Resources

### ISSUE THREAD

**Issue by smartsites** [aleron75/mageres#56]
Magento no longer provides the Magento 1 certification. I suggest to remove them from the list.

https://u.magento.com/

**Comment by aleron75** [comment]
Hello @smartsites thank for your suggestion.

To be sure I understand you properly, are you suggesting o remove the magecert.com URL and/or something else?

Thanks,
Alessandro

**Comment by smartsites** [comment]
@aleron75 
I suggest to remove the following:

![image](https://user-images.githubusercontent.com/13835073/65033627-d8dc9a00-d95e-11e9-918e-a19274cf3a74.png)

**Comment by aleron75** [comment]
thanks @smartsites for clarifying, I'll do it asap

**Comment by aleron75** [comment]
I close this issue since I made suggested changes in commit 9f49ee042abd8a701e0a0de91b854537247af8ed

Thanks @smartsites
