### ISSUE TITLE
Travis awesomebot whitelisted URLs logic

### ISSUE THREAD

**Issue by sergey-nechaev** [aleron75/mageres#66]
@aleron75 What's the logic behind this?

`--white-list https://magesec.org,https://opensource.magento.com/contribution-day-handbook`

https://github.com/aleron75/mageres/blob/master/.travis.yml#L7

**Comment by aleron75** [comment]
Some URLs are ok but don't pass the awesome_bot's validation, I don't know why.
Thus, I whitelist and check them manually every now and then.

**Comment by sergey-nechaev** [comment]
Ok, thanks, closing.
