### ISSUE TITLE
Where to mention the Firegento Association

### ISSUE THREAD

**Issue by Flyingmana** [aleron75/mageres#7]
the Firegento association is a not unimportant part of the European Magento community, but Iam not sure where to mention them.

http://firegento.com/

**Comment by aleron75** [comment]
Firegento is a company, listing companies is out of the scope of this repo. 
Instead I was glad to list the Firegento's packages link.

**Comment by Flyingmana** [comment]
I think there is an important difference between a company and an association

**Comment by aleron75** [comment]
Ops sorry, I didn't get the point then. What about putting it into the "Forums/Comunity"? It is a community after all, isn't it? Let me know

**Comment by aleron75** [comment]
Otherwise we can create the "Associations" sublist

**Comment by aleron75** [comment]
In the "Associations" we can also put the Meet Magento Association: http://www.meet-magento.com/meet-magento-association/

**Comment by Flyingmana** [comment]
an own Associations sublist sounds more matching, as they dont really have a forum or open community place.

**Comment by aleron75** [comment]
Done it! Thank you for your contributions, very appreciated!

**Comment by razbakov** [comment]
:+1:
