### ISSUE TITLE
Proper URL checking flow

### ISSUE THREAD

**Issue by sergey-nechaev** [aleron75/mageres#71]
**Problem**

Resources URLs can stop working randomly, but we will know about this only on the next PR. 

**Another problem**

PR can be good itself, but the build will fail when an unrelated URL stopped working.

**Solution**

1. Remove the check from the Travis
1. Install some kind of URL checker bot that will work daily and create an issue when some URL is not responsive for X days. Something like this - https://github.com/marketplace/imgbot. I have not found anything related to URLs checking, but I guess this could be achieved using the GitHub actions: https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

**Comment by aleron75** [comment]
Hello @sergey-nechaev, thanks for your suggestions; I didn't explore GitHub actions yet but sooner or later I must find the time. 

Meanwhile, I've added a bash script to check the URLs manually.

**Comment by sergey-nechaev** [comment]
I don't know much about the GitHub Actions either, will comment here when in case I have any ideas.

**Comment by sergey-nechaev** [comment]
This will help: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

**Comment by sergey-nechaev** [comment]
Implemented in https://github.com/aleron75/mageres/commit/aa1965d2c076944617b0de3b87fe94d1c7610ecf
