### ISSUE TITLE
README should be generated automatically

### ISSUE THREAD

**Issue by sergey-nechaev** [aleron75/mageres#72]
I believe the README should be generated automatically on each pull. Not by the developer who changes the CSV file. 

I think it's possible with the GitHub Action, see https://github.com/technote-space/toc-generator as a sample.

**Comment by aleron75** [comment]
Hello @sergey-nechaev,
generating the README on each push seems a good idea so that we can just update the CSV file.

As for issue #71, I just need some time to explore GitHub actions.

Best.
Alessandro

**Comment by sergey-nechaev** [comment]
I've found a solution, testing it now.

**Comment by sergey-nechaev** [comment]
@aleron75 
Done on my fork, see how it works here - https://github.com/sergey-nechaev/mageres/commits/master
Sample PR to test action: https://github.com/sergey-nechaev/mageres/pull/1
Action code:  https://github.com/sergey-nechaev/mageres/blob/master/.github/workflows/update-readme.yml
Basically it runs `csv2md.php` on each commit and only if `README` is changed - it will create a new commit with a changed `README`.

![image](https://user-images.githubusercontent.com/3796512/97783593-aa4d6d00-1bba-11eb-86e1-3518c7be9035.png)

**Comment by aleron75** [comment]
Hi @sergey-nechaev I couldn't push to your fork but if you tried and it works, please submit a PR and let's begin using it.
Good job!

**Comment by sergey-nechaev** [comment]
Pushed live with https://github.com/aleron75/mageres/commit/3b5eed1f233614de32be5355d56d9086862326d7
