### ISSUE TITLE
MageDerby is down

### ISSUE THREAD

**Issue by sergey-nechaev** [aleron75/mageres#75]
https://magederby.com/ is down for weeks already, not sure if they will be back or not.

Can somebody message them on https://twitter.com/magederby?

**Comment by aleron75** [comment]
Not sure if it's temporary down or it reached the end of life, I'll try to ask.

**Comment by aleron75** [comment]
Sent a DM on Twitter, let's wait for a reply. Thanks for pointing it out @sergey-nechaev

**Comment by aleron75** [comment]
The replied:

>Autorenew was off but it will be fixed soon.

So let's leave it in the list.

I keep the issue open as a reminder for future check.

**Comment by aleron75** [comment]
I still see several sites other than magederby that don't work properly: 

https://travis-ci.com/github/aleron75/mageres/builds/172920540

I'm going to remove them, will add again in case they recover.

**Comment by sergey-nechaev** [comment]
> I still see several sites other than magederby that don't work properly:
> 
> https://travis-ci.com/github/aleron75/mageres/builds/172920540
> 
> I'm going to remove them, will add again in case they recover.

It looks more like the awesome not issue for me. The sites you mentioned still work for me in a  browser

**Comment by aleron75** [comment]
I also checked them with another service and they don't seem to work:

- https://downforeveryoneorjustme.com/magemeter.com
- https://downforeveryoneorjustme.com/aionhill.com
- https://downforeveryoneorjustme.com/eschrade.com
- https://downforeveryoneorjustme.com/newsgento.com
- https://downforeveryoneorjustme.com/magederby.com

**Comment by sergey-nechaev** [comment]
Nothing from this list is loading properly for me. I see you've removed it, closing.
