### ISSUE TITLE
Should we remove (or archive somewhere else) Magento 1 resources?

### ISSUE THREAD

**Issue by aleron75** [aleron75/mageres#76]
Hello @sergey-nechaev, what do you think about removing all resources related to Magento 1?
Maybe we could move them in a secondary file (e.g. `README.M1.md`).
Let me know what do you think about it.
Thanks!

**Comment by sergey-nechaev** [comment]
Sorry, I meant it's a good idea to archive the data, not to remove it.

**Comment by aleron75** [comment]
Archived M1 resources in a separate file.

**Comment by sreichel** [comment]
Hey,

am i allowd to use M1-Readme for openmage.org?

(If you dont want to support M1 anymore, maybe point user to OM?)

**Comment by aleron75** [comment]
Hi @sreichel, of course, you are allowed.

>maybe point users to OM?

There is a link in M1 "Other Resources" that points to OpenMage, it's entitled "Magento LTS".

Furthermore, if you like to maintain the M1 resources list I can add you as a collaborator, let me know.

**Comment by sergey-nechaev** [comment]
@aleron75 
What about 
* [MageWorx on Magento 1](https://www.mageworx.com/blog/magento/)
* [Maxime Huran on Magento 1](https://www.maximehuran.fr/en/category/magento-one/)

I think it should be moved to M1 README too.

**Comment by aleron75** [comment]
Hi @sergey-nechaev, it's likely I missed something, you are perfectly right.

**Comment by aleron75** [comment]
@sergey-nechaev fixed with commit 6ccb278596d315eaef8570b1e4e2b3c92c73bac0
I leave the issue open for a while to give @sreichel time to reply.

**Comment by sreichel** [comment]
Thanks, No need to add me as collaborator, i have nothing to add :)

If openmage can re-use your docs it could be a great addition. Just dont wanted to copy&paste.

**Comment by sergey-nechaev** [comment]
@sreichel you can use the docs, see the license https://github.com/aleron75/mageres/blob/master/LICENSE

**Comment by colinmollenhour** [comment]
It would be great for the OpenMage community to add at the top some mention of OpenMage as a continued-support alternative to Magento 1 and also on the main README.md change some of the language around "archiving" to something more like "migrated". :)  Would you prefer me to submit a PR for such changes?

**Comment by aleron75** [comment]
Sorry @colinmollenhour I closed this issue by accident.

>Would you prefer me to submit a PR for such changes?

yes, thank you!

**Comment by aleron75** [comment]
Side note for @colinmollenhour: the `README.md` is auto-generated by the `csv2md.php` so while you can edit the `README-M1.md` manually, please don't do the same for `README.md`, rather change the text in `csv2md.php` or suggest the change you wish here, so that I can do that.

Thanks again.

**Comment by sreichel** [comment]
> Side note for @colinmollenhour: the `README.md` is auto-generated by the `csv2md.php` so while you can edit the `README-M1.md` manually

To keep automation, why not add removed lines `resources.csv` to `resources-m1.csv?

**Comment by aleron75** [comment]
@sreichel 

>why not add removed lines from resources.csv to resources-m1.csv?

since I won't update that list of resources anymore I didn't think to add any automation
