### ISSUE TITLE
Source for "README template for Magento modules" resource

### ISSUE THREAD

**Issue by sergey-nechaev** [aleron75/mageres#77]
[README template for Magento modules](https://gist.github.com/magento-docbot/dfb8cc7db6519da14fc92b890d49b7d3)

So we have this resource and I am interested in how official and actual it is. But I can not locate any referring docs. It was added in this commit: https://github.com/aleron75/mageres/commit/0da26ec949b10df79288db626ec184de21bba402

@aleron75 Any insights?

**Comment by aleron75** [comment]
Hi @sergey-nechaev I don't remember the source of this resource, it's just as opinionated as other templates.

I also found this other one: https://github.com/AOEpeople/Magento-2-Module-Skeleton/blob/master/src/doc/README.template.md

If you think it can generate confusion, let's remove it.

**Comment by sergey-nechaev** [comment]
Ok, I will research this. I believe the latest Magento docs should have some suggestions on the topic.

**Comment by aleron75** [comment]
Thanks, let me know if I can help somehow.
